CarDealer/Models/Salesperson.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CarDealer.Models
{
    public class Salesperson
    {
        public int SalespersonID { get; set; }
        
        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        
        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Hire Date")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public DateTime? HireDate { get; set; }
        
        public string Email { get; set; }
        
        public double? Salary { get; set; }
    }
}

CarDealer/Controllers/SalespersonController.cs
using CarDealer.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarDealer.Controllers
{
    public class SalespersonController : Controller
    {
        public IActionResult Index()
        {
            List<Salesperson> salespeople;
            using (var _context = new DealershipContext())
            {
                salespeople = _context.Salesperson.OrderBy(x => x.FirstName).ToList();
            }
            return View(salespeople);
        }

        public IActionResult Create()
        {
            Salesperson salesperson = new Salesperson();
            return View("SalespersonForm", salesperson);
        }

        public IActionResult Edit(int id)
        {
            Salesperson model;
            using (var _context = new DealershipContext())
            {
                model = _context.Salesperson.Single(x => x.SalespersonID == id);
            }
            return View("SalespersonForm", model);
        }

        public IActionResult Details(int id)
        {
            Salesperson model;
            using (var _context = new DealershipContext())
            {
                model = _context.Salesperson.Single(x => x.SalespersonID == id);
            }
            return View(model);
        }

        public IActionResult Delete(int id)
        {
            Salesperson model;
            using (var _context = new DealershipContext())
            {
                model = _context.Salesperson.Single(x => x.SalespersonID == id);
            }
            return View(model);
        }


        [HttpPost]
        public IActionResult Save(Salesperson model)
        {
            if(!ModelState.IsValid)
            {
                return View("SalespersonForm", model);
            }

            using (var _context = new DealershipContext())
            {
                if(model.SalespersonID == 0)
                {
                    _context.Salesperson.Add(model);
                }
                else
                {
                    var modelInDb = _context.Salesperson.
                        Single(x => x.SalespersonID == model.SalespersonID);

                    modelInDb.FirstName = model.FirstName;
                    modelInDb.LastName = model.LastName;
                    modelInDb.HireDate = model.HireDate;
                    modelInDb.Email = model.Email;
                    modelInDb.Salary = model.Salary;
                }
                _context.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Delete(Salesperson model)
        {
            using (var _context = new DealershipContext())
            {
                _context.Salesperson.Remove(model);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

    }
}

CarDealer/Views/Salesperson/Delete.cshtml
@model Salesperson 
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>

<div class="row">
    <div class="col-4">
        <h5>Salesperson</h5>
        <hr />

        @using (Html.BeginForm())
        {
            <table class="table table-borderless">
                <tr>
                    <th>First Name</th>
                    <td>@Model.FirstName</td>
                </tr>
                <tr>
                    <th>Last Name</th>
                    <td>@Model.LastName</td>
                </tr>
                <tr>
                    <th>Hire Date</th>
                    <td>@Model.HireDate</td>
                </tr>
                <tr>
                    <th>Email</th>
                    <td>@Model.Email</td>
                </tr>
                <tr>
                    <th>Salary</th>
                    <td>@Model.Salary</td>
                </tr>
            </table>

            @Html.HiddenFor(m => m.SalespersonID)

            <input type="submit" value="Delete" class="btn btn-danger" />
            <span> | </span>
            @Html.ActionLink("Back to list", "Index")
        }

    </div>
</div>

CarDealer/Views/Salesperson/Details.cshtml
@model Salesperson 
@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>
<h3>Salesperson</h3>
<hr />
<div class="row">
    <div class="col-md-4">

        <table class="table table-borderless">
            <tr>
                <th>First Name</th>
                <td>@Model.FirstName</td>
            </tr>
            <tr>
                <th>Last Name</th>
                <td>@Model.LastName</td>
            </tr>
            <tr>
                <th>Hire Date</th>
                <td>@Model.HireDate</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>@Model.Email</td>
            </tr>
            <tr>
                <th>Salary</th>
                <td>@Model.Salary</td>
            </tr>
        </table>


    </div>
    <div class="col-md-12">
        @Html.ActionLink("Edit", "Edit", routeValues: new { id = Model.SalespersonID })
        <span> | </span>
        @Html.ActionLink("Back to list", "Index")
    </div>

</div>

CarDealer/Views/Salesperson/Index.cshtml
@model IList<Salesperson> 

@{
    ViewData["Title"] = "Index";
}

<h1>Salespeople</h1>

@Html.ActionLink("Create New", "Create")

<table class="table">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>@item.FirstName</td>
                    <td>@item.LastName</td>
                    <td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", routeValues: new { id = item.SalespersonID }) |
                        @Html.ActionLink("Details", "Details", routeValues: new { id = item.SalespersonID }) |
                        @Html.ActionLink("Delete", "Delete", routeValues: new { id = item.SalespersonID })
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

CarDealer/Views/Salesperson/SalespersonForm.cshtml
@model Salesperson
 
@{
    ViewData["Title"] = "Salesperson Form";
}

@{
    string heading = Model.SalespersonID == 0 ? "Create" : "Edit";
}

<h1>@heading</h1>

@using (Html.BeginForm("Save", "Salesperson"))
{
    <div class="row">
        <div class="col-4">
            <h3>Salespersons</h3>
            <hr />
            <div class="form-group">
                @Html.LabelFor(m => m.FirstName, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(m => m.FirstName, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.FirstName, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.LastName, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(m => m.LastName, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.LastName, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.HireDate, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(m => m.HireDate, htmlAttributes: new { @class = "form-control", type = Model.SalespersonID == 0 ? "datetime-local": "" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Email, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(m => m.Email, htmlAttributes: new { @class = "form-control" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Salary, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(m => m.Salary, htmlAttributes: new { @class = "form-control" })
            </div>

            @Html.HiddenFor(m => m.SalespersonID)

            @{
                string buttonValue = Model.SalespersonID == 0 ? "Create" : "Save";
            }
            <div class="form-group">
                <input type="submit" value=@buttonValue class="btn btn-primary" />
            </div>

            <div class="form-group">
                @Html.ActionLink("Back to list", "Index")
            </div>
        </div>
    </div>

}