CarDealer/Models/Buyer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace CarDealer.Models
{
    public class Buyer
    {
        public int BuyerID { get; set; }
        
        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        
        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        
        [Required]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }
        
        public string Address { get; set; }
        
        public string City { get; set; }
        
        public string State { get; set; }
        
        public int? Zip { get; set; }

        [NotMapped]
        public string BuyerName
        {
            get
            {
                return string.Format("{0} {1}", FirstName, LastName);
            }
        }
    }
}

CarDealer/Models/BuyerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarDealer.Models
{
    public class BuyerViewModel
    {
        public Buyer Buyer { get; set; }
        public IList<Sale> Sales { get; set; }
    }
}

CarDealer/Controllers/BuyerController.cs
using CarDealer.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarDealer.Controllers
{
    public class BuyerController : Controller
    {
        public IActionResult Index()
        {
            List<Buyer> buyers;
            using (var _context = new DealershipContext())
            {
                buyers = _context.Buyer.OrderBy(x => x.FirstName).ToList();
            }
            return View(buyers);
        }

        public IActionResult Create()
        {
            Buyer buyer = new Buyer();
            return View("BuyerForm", buyer);
        }

        public IActionResult Edit(int id)
        {
            Buyer buyer;
            using (var _context = new DealershipContext())
            {
                buyer = _context.Buyer.Single(b => b.BuyerID == id);
            }
            return View("BuyerForm", buyer);
        }

        public IActionResult Details(int id)
        {
            BuyerViewModel viewModel = new BuyerViewModel();
            using (var _context = new DealershipContext())
            {
                viewModel.Buyer = _context.Buyer.Single(b => b.BuyerID == id);
                viewModel.Sales = _context.Sale.
                    Include(x => x.Vehicle).
                    OrderByDescending(x => x.SaleDate).
                    Where(x => x.BuyerID == id).
                    ToList();
            }
            return View(viewModel);
        }

        public IActionResult Delete(int id)
        {
            Buyer buyer;
            using (var _context = new DealershipContext())
            {
                buyer = _context.Buyer.Single(b => b.BuyerID == id);
            }
            return View(buyer);
        }

        [HttpPost]
        public IActionResult Save(Buyer buyer)
        {
            if(!ModelState.IsValid)
            {
                return View("BuyerForm");
            }

            using (var _context = new DealershipContext())
            {
                if(buyer.BuyerID == 0)
                {
                    _context.Buyer.Add(buyer);
                }
                else
                {
                    Buyer buyerInDb = _context.Buyer.Single(b => b.BuyerID == buyer.BuyerID);

                    buyerInDb.FirstName = buyer.FirstName;
                    buyerInDb.LastName = buyer.LastName;
                    buyerInDb.PhoneNumber = buyer.PhoneNumber;
                    buyerInDb.Address = buyer.Address;
                    buyerInDb.City = buyer.City;
                    buyerInDb.State = buyer.State;
                    buyerInDb.Zip = buyer.Zip;
                }

                _context.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Delete(Buyer buyer)
        {
            using (var _context = new DealershipContext())
            {
                _context.Buyer.Remove(buyer);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }

}

CarDealer/Views/Buyer/BuyerForm.cshtml
@model Buyer

@{
    ViewData["Title"] = "Create";
}

@{ 
    string heading = Model.BuyerID == 0 ? "Create" : "Edit";
}

<h1>@heading</h1>

@using (Html.BeginForm("Save", "Buyer"))
{
    <div class="row">
        <div class="col-4">
            <h3>Buyer</h3>
            <hr />
            <div class="form-group">
                @Html.LabelFor(m => m.FirstName, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(m => m.FirstName, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.FirstName, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.LastName, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(m => m.LastName, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.LastName, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.PhoneNumber, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(m => m.PhoneNumber, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.PhoneNumber, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Address, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(m => m.Address, htmlAttributes: new { @class = "form-control" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.City, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(m => m.City, htmlAttributes: new { @class = "form-control" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.State, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(m => m.State, htmlAttributes: new { @class = "form-control" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Zip, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(m => m.Zip, htmlAttributes: new { @class = "form-control" })
            </div>

            @Html.HiddenFor(m => m.BuyerID)

            @{ 
                string buttonValue = Model.BuyerID == 0 ? "Create" : "Save";
            }  
            <div class="form-group">
                <input type="submit" value=@buttonValue class="btn btn-primary" />
            </div>

            <div class="form-group">
                @Html.ActionLink("Back to list", "Index")
            </div>
        </div>
    </div>

}

CarDealer/Views/Buyer/Delete.cshtml
@model Buyer

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>
<h3>Are you sure you want to delete this?</h3>

<div class="row">
    <div class="col-4">
        <h5>Buyer</h5>
        <hr />

        @using (Html.BeginForm())
        {
            <table class="table table-borderless">
                <tr>
                    <th>First Name</th>
                    <td>@Model.FirstName</td>
                </tr>
                <tr>
                    <th>Last Name</th>
                    <td>@Model.LastName</td>
                </tr>
                <tr>
                    <th>Phone Number</th>
                    <td>@Model.PhoneNumber</td>
                </tr>
                <tr>
                    <th>Address</th>
                    <td>@Model.Address</td>
                </tr>
                <tr>
                    <th>City</th>
                    <td>@Model.City</td>
                </tr>
                <tr>
                    <th>State</th>
                    <td>@Model.State</td>
                </tr>
                <tr>
                    <th>Zip</th>
                    <td>@Model.Zip</td>
                </tr>
            </table>

            @Html.HiddenFor(m => m.BuyerID)

            <input type="submit" value="Delete" class="btn btn-danger" />
            <span> | </span>
            @Html.ActionLink("Back to list", "Index")
        }

    </div>
</div>

CarDealer/Views/Buyer/Details.cshtml
@model BuyerViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>
<h3>Buyer</h3>
<hr />
<div class="row">
    <div class="col-md-4">

        <table class="table table-borderless">
            <tr>
                <th>First Name</th>
                <td>@Model.Buyer.FirstName</td>
            </tr>
            <tr>
                <th>Last Name</th>
                <td>@Model.Buyer.LastName</td>
            </tr>
            <tr>
                <th>Phone Number</th>
                <td>@Model.Buyer.PhoneNumber</td>
            </tr>
            <tr>
                <th>Address</th>
                <td>@Model.Buyer.Address</td>
            </tr>
            <tr>
                <th>City</th>
                <td>@Model.Buyer.City</td>
            </tr>
            <tr>
                <th>State</th>
                <td>@Model.Buyer.State</td>
            </tr>
            <tr>
                <th>Zip</th>
                <td>@Model.Buyer.Zip</td>
            </tr>
        </table>


    </div>
    <div class="col-md-12">
        @if (Model.Sales != null && Model.Sales.Count > 0)
        {
            <table class="table">
                <thead>
                    <tr>
                        <th>Sale Date</th>
                        <th>Sale Price</th>
                        <th>Sale Vehicle</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Sales)
                    {
                        <tr>
                            <td>@item.SaleDate</td>
                            <td>@item.SalePrice</td>
                            <td>
                                @item.Vehicle.Year @item.Vehicle.Color
                                @item.Vehicle.Manufacturer @item.Vehicle.Model
                                @item.Vehicle.Mileage
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }

        @Html.ActionLink("Edit", "Edit", routeValues: new { id = Model.Buyer.BuyerID })
        <span> | </span>
        @Html.ActionLink("Back to list", "Index")
    </div>
    
</div>

CarDealer/Views/Buyer/Index.cshtml
@model IList<Buyer>

@{
    ViewData["Title"] = "Index";
}

<h1>Buyers</h1>

@Html.ActionLink("Create New", "Create")

<table class="table">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
        </tr>
    </thead>
    <tbody>
        @if(Model != null)
        {
            foreach (var item in Model)
            {
        <tr>
            <td>@item.FirstName</td>
            <td>@item.LastName</td>
            <td>
            <td>
                @Html.ActionLink("Edit", "Edit", routeValues: new { id=item.BuyerID}) |
                @Html.ActionLink("Details", "Details", routeValues: new { id = item.BuyerID }) |
                @Html.ActionLink("Delete", "Delete", routeValues: new { id = item.BuyerID })
            </td>
        </tr>
            }
        }
    </tbody>
</table>